### ISSUE TITLE
How to rewrite the excel without covering the old things

### ISSUE THREAD

**Issue by EMDCYY** [python-excel/xlwt#105]
I use the xlwt to write and save an excel. But I have a question how to rewrite the excel.
For example:
        excel = xlwt.Workbook()
        sheet = excel.add_sheet('Hello')
        sheet.write(0, 1, 'world')
        excel.save('ABC.xls')

After save the excel, how can I reopen the excel again and write new things into the 'Hello' sheet without coving the old things?

**Comment by cjw296** [comment]
This is not a mailing list.
