### ISSUE TITLE
Easyxf pattern_fore_colour not working

### ISSUE THREAD

**Issue by MehdiBela** [python-excel/xlwt#107]
Hello,

First of all thanks for this wonderful package, it has been very useful to me ! 

My issue concern cell styling using easyxf. I'm trying to apply conditional styling to set cell background color to green or red. Below code sample runs fine but fore_colour is not applied. I've tried many syntaxes such 'pattern: pattern_fore_colour red', everytimes it compilates but is not applied. When I do the same with font color, it works fines. I'm quite troubled there and I'll actually use a bit of a help.
```

                if val_l != val_r :
                    font_style = xlwt.easyxf('pattern: fore_colour red, back_colour red;')
                    #font_style = xlwt.easyxf('font: color red')
                    ws_diff.write(row_num, j-1, val_l, font_style)
                    ws_diff.write(row_num, j-1+len(elem_left.values()[0]), val_r, font_style)
                elif val_l == val_r:
                    font_style = xlwt.easyxf('pattern: pattern_fore_colour green, pattern_back_colour green')
                    ws_same.write(row_num, j-1, val_l, font_style)
                    ws_same.write(row_num, j-1+len(elem_left.values()[0]), val_r, font_style)


```
Thanks in advance for any answer.

**Comment by sjmachin** [comment]
Please ask your question in a more appropriate forum e.g. https://groups.google.com/forum/#!forum/python-excel
