### ISSUE TITLE
How to use self-defined colour

### ISSUE THREAD

**Issue by Matiz7** [python-excel/xlwt#108]
pattern = xlwt.Pattern()
    pattern.pattern = xlwt.Pattern.SOLID_PATTERN
    pattern.pattern_fore_colour =  5 # May be: 8 through 63. 0 = Black, 1 = White, 2 = Red, 3 = Green, 4 = Blue, 5 = Yellow, 6 = Magenta, 7 = Cyan .....

    how can I set colour to #8FBC8F     like this ?

**Comment by cjw296** [comment]
This is not a mailing list. Suggest you use openpyxl.
