### ISSUE TITLE
change flag to "cell_overwrite_ok=False"

### ISSUE THREAD

**Issue by shmelevsky** [python-excel/xlwt#127]
Hello 
I added  sheet with flag cell_overwrite_ok=False.
I need this flag, becouse i use  exception  mechanism that doesn`t give  overwrite some cells.
But in code bellow i whant to change flag cell_overwrite_ok to True.
becouse i have to make borders in my sheet.
How can i change this flag?
Thank you!

**Comment by shmelevsky** [comment]
Hmm.
When i added border, cell overwrited.
How can i make border without overwrite data in a cell?

**Comment by shmelevsky** [comment]
I resolved issue. I imported xlrd
Code reads value from the cell and then rewrites value  with new style (border)
But i am not sure it is correctly.

**Comment by cjw296** [comment]
This is not a mailing list.
