### ISSUE TITLE
New Worksheet.add_bitmap method to avoid disk I/O

### ISSUE THREAD

**Issue by rossigee** [python-excel/xlwt#37]
Hi,

I have a script that prepares an XLS report that includes several bitmaps that I've converted in memory from JPEGs. The problem with the existing API method for the task, 'Worksheet.insert_bitmap', is that it relies on (expects) the bitmap data to be on file. I have it in memory already, and I don't want to unnecessarily write it out to disk. For me, this required two minor changes to xlwt.

First, a patch for Bitmap that delegates the main work of the '_process_bitmap(file)' method down into a new '_process_bitmap_data(data)' method that allows the caller to bypass the file open/read/close part of the operation to create a Bitmap object from their in-memory copy. Basically...

<pre>
diff --git a/xlwt/Bitmap.py b/xlwt/Bitmap.py
index ef50d2a..31e15ac 100644
--- a/xlwt/Bitmap.py
+++ b/xlwt/Bitmap.py
@@ -196,8 +196,11 @@ def _process_bitmap(bitmap):
     try:
         # Slurp the file into a string.
         data = fh.read()
+        return _process_bitmap_data(data)
     finally:
         fh.close()
+
+def _process_bitmap_data(data):
     # Check that the file is big enough to be a bitmap.
     if len(data) &lt;= 0x36:
         raise Exception("bitmap doesn't contain enough data.")
</pre>

Secondly, a patch for Worksheet that delegates the main work of the 'insert_bitmap' method to an 'add_bitmap' method to allow the caller to add their new Bitmap directly to the worksheet...

<pre>
diff --git a/xlwt/Worksheet.py b/xlwt/Worksheet.py
index cd90ccd..161f648 100644
--- a/xlwt/Worksheet.py
+++ b/xlwt/Worksheet.py
@@ -1063,7 +1063,9 @@ class Worksheet(object):
     def insert_bitmap(self, filename, row, col, x = 0, y = 0, scale_x = 1, scale_y = 1):
         bmp = Bitmap.ImDataBmpRecord(filename)
         obj = Bitmap.ObjBmpRecord(row, col, self, bmp, x, y, scale_x, scale_y)
+        self.add_bitmap(obj, bmp)
 
+    def add_bitmap(self, obj, bmp):
         self.__bmp_rec += obj.get() + bmp.get()
 
     def col(self, indx):
</pre>

This allows the calling code to work like this...

<pre>
class OurBiffRecord(xlwt.BIFFRecords.BiffRecord):
    _REC_ID = 0x007F

    def __init__(self, data):
        xlwt.BIFFRecords.BiffRecord.__init__(self)

        self.width, self.height, self.size, data = xlwt.Bitmap._process_bitmap_data(data)
        # Write the IMDATA record to store the bitmap data
        cf = 0x09
        env = 0x01
        lcb = self.size
        self._rec_data = struct.pack("&lt;HHL", cf, env, lcb) + data
</pre>

<pre>
				jpegobj = PIL.Image.open(StringIO.StringIO(jpegdata))
				bmpbuf = StringIO.StringIO()
				jpegobj.save(bmpbuf, "BMP")
				bmp = OurBiffRecord(bmpbuf.getvalue())
				obj = xlwt.Bitmap.ObjBmpRecord(self.row, col, sheet, bmp, 0, 0, 1, 1)
				sheet.add_bitmap(obj, bmp)
				bmpbuf.close()
</pre>

It could probably be improved upon in order to make the calling code cleaner and more concise, but I'm not in a position to do that now, and this was the best approach I could come up with that was also the least-intrusive to the xlwt codebase as possible in the time available.

Anyway, throwing it out there for discussion.

Hopefully the maintainers will consider it, or some variant of it, for inclusion. It would make at least my life easier not to have to roll a custom one for my deployments :) If the patch needs more in the way of comments/tests or whatever, I'll happily take a look, if you point me in the right direction.

Thanks,

--
Ross

**Comment by cjw296** [comment]
The pull requests have been addressed, sadly we'll need a new one now, closing this issue as there's not benefit to it being open ;-)
