### ISSUE TITLE
New release (one year more)

### ISSUE THREAD

**Issue by avelino** [python-excel/xlwt#47]
Hi guys, xlwt not generate release more one year, let's go release generate?

'm used in Open Mining (BI application in Python)
https://github.com/avelino/mining/issues/93

**Comment by cjw296** [comment]
#24 was not "fixed", @sjmachin pointed out that what you were trying to do was not possible, so not sure why you're asking for a release?

Anyway, not really a good use of an issue, how about asking on the mailing list next time?
