### ISSUE TITLE
There are 36 formats but 38 loops

### ISSUE THREAD

**Issue by psionic12** [python-excel/xlwt#56]
In Style.py, _std_num_fmt_list has 36 formats, but in line 79:
        for fmtidx, fmtstr in zip(range(0, 23), StyleCollection._std_num_fmt_list[0:23]):
            self._num_formats[fmtstr] = fmtidx
        for fmtidx, fmtstr in zip(range(37, 50), StyleCollection._std_num_fmt_list[23:]):
            self._num_formats[fmtstr] = fmtidx

the dict got two none value. In my case, unicode(s,encoding) got a 'none' and the program crashed.

**Comment by cjw296** [comment]
out of date
