### ISSUE TITLE
Would it be possible to have xlwt save with metadata so the unix file tool can identify the saved file properly?

### ISSUE THREAD

**Issue by Celc** [python-excel/xlwt#59]
This was causing some confusion because the framework I was using forces a mime check via `file` and it's not being identified as `application/vnd.ms-excel`.

```bash
$ file -I xlwt-saved.xls 
xlwt-saved.xls: CDF V2 Document, No summary info; charset=binary
$ file -I excell-saved.xls 
excell-saved.xls: application/vnd.ms-excel; charset=binary
```

The relevant file format checking code seem to be here: https://github.com/file/file/blob/d9e9aa9f06757947a1e51f80925445b2f18a6fc3/magic/Magdir/msdos#L519

**Comment by cjw296** [comment]
Please submit a pull request with the code changes and an appropriate test...

**Comment by turicas** [comment]
[A user is requesting this feature in the rows library](https://github.com/turicas/rows/issues/64) (which uses xlwt). It'd be nice if somebody implement this (I don't have enough time for this now, unfortunately).
