### ISSUE TITLE
Add More Formula Functions

### ISSUE THREAD

**Issue by speedplane** [python-excel/xlwt#62]
It looks like xlwt only supports a few basic functions (`if`, `sum`, `max`, `min`, and `choose`). It would be fantastic if additional formulas were added. 

I'm specifically looking at `averageif` which is difficult to implement without a specific formula function.

**Comment by sjmachin** [comment]
xlwt supports about 340 functions; see source file ExcelMagic.py. The 5 that you listed are special-cased in the code generation stage.

averageif() was introduced in Excel2007; xlwt supports up to Excel 2003.

**Comment by speedplane** [comment]
Thanks. I realized I can basically create `averageif` using `sumif` and `countif`, which are supported by `xwlt`.
