### ISSUE TITLE
What happens if the len(sheet_name) > 31?

### ISSUE THREAD

**Issue by Abipathak** [python-excel/xlwt#63]
This is my error 
raise Exception("invalid worksheet name %r" % sheetname)
Exception: invalid worksheet name u'Civil/Structural'

**Comment by cjw296** [comment]
Sheetnames greater than 31 characters are not supported by Excel.
This is a question, in future please ask questions on the python-excel google group.

**Comment by sjmachin** [comment]
This an Excel issue, not an xlwt issue.
u'Civil/Structural' doesn't appear to contain more than 31 characters.

Clue: Fire up the Excel UI and try renaming "Sheet 1" to "Fu/bar".

Here's the full scoop from xlwt's Utils.py:
def valid_sheet_name(sheet_name):
    if sheet_name == u"" or sheet_name[0] == u"'" or len(sheet_name) > 31:
        return False
    for c in sheet_name:
        if c in u"[]:\\?/*\x00":
            return False
    return True

Pecking list for solving problems like this:
a.Check the behaviour of Excel
b.looking in the source of (in this case) xlwt, You will be lead (in this case) to the function above.
d. google("excel valid worksheet name")
d. ask in the python-excel google-group
d report a defect here on github.

HTH,
John
