### ISSUE TITLE
Convert HTML rich code to Excel application

### ISSUE THREAD

**Issue by SudheerVusa** [python-excel/xlwt#64]
Hi,

Could any body let me know how to convert the HTML report file stored in my local system to an excel application.

I tried reading the data by the function "open' and used the data to paste it in the excel using
sheet.cell(row=1,column=1).value = data

but this is writing the source code into the cell, but I want it to paste the data as like HTML rich data.

Regards,
Sudheer Vusa

**Comment by cjw296** [comment]
This is not a mailing list. Use the mailing list.
