### ISSUE TITLE
Properly representing nan values

### ISSUE THREAD

**Issue by durden** [python-excel/xlwt#69]
I've been using xlwt for a long time, and it's pretty flawless.  However, I've recently run into an issue where I'm writing data that is `nan`, specifically `numpy.nan`.  The resulting excel file represents this value as a very large number such as 1.0e208.  Would it make sense to detect that a value `isnan` using `math.isnan` (to avoid using numpy.isnan) and write something more excel friendly?

The trouble is I'm not entirely sure what 'excel friendly' means.  Maybe [this function](https://github.com/python-excel/xlwt/blob/master/xlwt/Row.py#L234) could use `math.isnan` then write out something like `#NUM!` or something else to represent nan as [suggested here](http://stackoverflow.com/questions/15704538/how-can-i-express-nan-values-in-excel).

**Comment by cjw296** [comment]
A patch using math.isnan and writing a #NUM! would be welcomed.

**Comment by durden** [comment]
I submitted a [pull request](https://github.com/python-excel/xlwt/pull/79) for this.

**Comment by cjw296** [comment]
We can track on the pull request, happy to re-open when you have those tests passing.
