### ISSUE TITLE
Python 3 errors when installing 1.0.0 from PyPI

### ISSUE THREAD

**Issue by alexanderlukanin13** [python-excel/xlwt#71]
How to reproduce:

    python3 -m venv foo
    source foo/bin/activate
    pip install xlwt

Output contains Python 3 compatibility errors like this:

    *** Error compiling '/tmp/pip-pnr0ax7z-build/xlwt/examples/wsprops.py'...
      File "/tmp/pip-pnr0ax7z-build/xlwt/examples/wsprops.py", line 83
        print ws.name
               ^
    SyntaxError: Missing parentheses in call to 'print'

All of these errors are fixed in master. Apparently, [xlwt-1.0.0-py2.py3-none-any.whl](https://pypi.python.org/packages/py2.py3/x/xlwt/xlwt-1.0.0-py2.py3-none-any.whl) contains old code.

**Comment by cjw296** [comment]
That's sad :-(

Pull requests to fix greatfuly received!

**Comment by alexanderlukanin13** [comment]
As far as I see, it's already fixed, you only need to bump version to 1.0.1 and upload to PyPI

    python setup.py sdist bdist_wheel upload

**Comment by alexgleason** [comment]
Hi, also having this problem. Any luck? Thank you. :smile:

**Comment by fbender** [comment]
See also #84

**Comment by cjw296** [comment]
1.1.1 being released today!
