### ISSUE TITLE
Bundled antlr file status unclear.

### ISSUE THREAD

**Issue by leamas** [python-excel/xlwt#73]
The distribution contains a file xlwt/antlr.py. According to the comments in file it should be a copy of the 2.7.7 antlr2 release. However, it's seemingly not. When I download a 2.7.7 release from http://www.antlr2.org i get a diff of about 330 lines.

Bundling files this way creates hard to solve problems for distributions which want to avoid it for distribution-wide reasons. In previous versions is has been possible to unbundle antlr.py and use the official 2.7.5 antlr package instead. However, with 1.0.0 the build breaks with errors in antlr.py unless the patched variant is used. 

I understand that the python-xlwt code needs it's own antlr.py file, packaging certainly  isn't the only usecase. However,  packaging-wise the antlr.py patches  is a bug which should be fixed by upstreaming  and/or reverting them.

**Comment by cjw296** [comment]
Please treat this file as an internal implementation detail of xlwt and do not attempt to do anything clever with packaging.
