### ISSUE TITLE
Sorting Worksheets in Workbook

### ISSUE THREAD

**Issue by smsteel** [python-excel/xlwt#78]
It would've been really useful to have this feature.

Currently, i inherited from Workbook to make this work:

    from xlwt import Workbook

    class XLWTWorkbook(Workbook):

        @property
        def worksheets(self):
            return self._Workbook__worksheets

        @worksheets.setter
        def worksheets(self, worksheets):
            self._Workbook__worksheets = worksheets

And i'm doing like this:

`workbook.worksheets.sort(key=lambda worksheet: worksheet.id)`

`workbook.worksheets.sort(key=lambda worksheet: worksheet.name)`

**Comment by cjw296** [comment]
I'm not really sure what you're asking for, so please submit a pull request containing:

- tests to demonstrate what your change will enable
- the changes to support the tests.

cheers,

Chris
