### ISSUE TITLE
How to wrap text in a cell when using write_rich_text

### ISSUE THREAD

**Issue by leefionglee** [python-excel/xlwt#82]
Hi all,

I can use below code to highlight partial text content in a cell. As the text content is too long, how can I wrap the text so that it looks more visual friendly?  Thanks a lot!!

font0 = xlwt.easyfont('')
font1 = xlwt.easyfont('color_index red')

seg1 = ('BA LA BA LA BA LA BA LA BA LA BA LA', font1) # red
seg2 = ('BA LA BA LA BA LA BA LA BA LA BA LA', font0) # default 

tmp = (seg1, ) + (seg2, )

sheet.write_rich_text(1, 1, tmp)  **# how to wrap the text in a cell?**

**Comment by cjw296** [comment]
This is a question and it belongs on the mailing list.
