### ISSUE TITLE
Wrong output excel file with python 3

### ISSUE THREAD

**Issue by exvion** [python-excel/xlwt#84]
Read data from input.xls and write output.xls. I can't open output-python3.xls
```
import xlrd, xlwt
book = xlrd.open_workbook("input.xls")
sh = book.sheet_by_index(0)
wb = xlwt.Workbook()
ws = wb.add_sheet('Test')
i = 1
for r in range(7, sh.nrows):
    sku = int(sh.cell(r,0).value)
    name = sh.cell(r, 1).value
    ws.write(i, 0, sku)
    ws.write(i, 1, name)
    i += 1
wb.save('output.xls')
```

Python 2.7.11 xlrd (0.9.4) xlwt (1.0.0)
Python 3.5.1 xlrd (0.9.4) xlwt (1.0.0)

[Archive.zip](https://github.com/python-excel/xlwt/files/260034/Archive.zip)

**Comment by exvion** [comment]
I installed last version from github,  Thank you for fix https://github.com/python-excel/xlwt/pull/77
https://pypi.python.org/pypi/xlwt/1.0.0 has this bug, need new version 1.0.1

**Comment by fbender** [comment]
@cjw296 When do you expect to release an updated version fixing this issue?

**Comment by cjw296** [comment]
Soon!
