### ISSUE TITLE
Work with Formula for sheet names that are pure numbers

### ISSUE THREAD

**Issue by wlclive** [python-excel/xlwt#85]
Hello,

I was trying to assign formula which references sheet name of pure digits, eg. the sheet name "1120" indicates that the sheet is been constructed on 20th Nov. But when assigning the formula into a workbook, Workbook.add_sheet_reference() will treat it as an index (in string form) instead of a sheet name string. So I will ended up with an exception:
`Exception: Formula: sheet index (1120) >= number of sheets (10)`

I know this is intended. Is there any workaround for this kind of situation? Thanks in advance.

**Comment by sjmachin** [comment]
Note that if you type =1120!a1 into an Excel cell, the expected result happens (provided 1120 already exists as a sheet name). Check out what is showing in the formula bar; it's ='1120'!A1. Try wrapping apostrophes around your sheet names in xlwt.

**Comment by wlclive** [comment]
At the beginning I did wrap the sheet name with apostrophes, and it gave me the exception.

Currently my workaround is a new write_formula function that bypasses Workbook.add_sheet_reference() with my own version of add_sheet_reference(), which its ref0.isdigit() and ref1.isdigit() and related codes removed (ie. line 417, 423, 426, 430). This fixed my problem.

Cheers.

**Comment by cjw296** [comment]
Realistically, this is only going to be addressed if you submit a pull request containing:

- a test or two that reproduce the problem
- a code fix for the problem.

So, closing this issue for now...
