### ISSUE TITLE
Encoding creates issues on CentOs6

### ISSUE THREAD

**Issue by gabn88** [python-excel/xlwt#86]
I use xlwt on a Django installation, but it chokes on makesmessages. 

The error is: Unknown encoding: # -*- coding: windows-1252 -*- 

Is it safe to modify this to utf-8?

**Comment by cjw296** [comment]
"it chokes" is not very helpful. What's the full exception?

**Comment by gabn88** [comment]
xgettext: ./lib/python3.4/site-packages/xlwt/Bitmap.py:1: Unknown encoding "windows-1251". Proceeding with ASCII instead.
xgettext: ./lib/python3.4/site-packages/xlwt/Cell.py:1: Unknown encoding "windows-1252". Proceeding with ASCII instead.
xgettext: ./lib/python3.4/site-packages/xlwt/Column.py:1: Unknown encoding "windows-1252". Proceeding with ASCII instead.

CommandError: errors happened while running xgettext on CompoundDoc.py
xgettext: ./lib/python3.4/site-packages/xlwt/CompoundDoc.py:1: Unknown encoding "windows-1252". Proceeding with ASCII instead.
xgettext: Non-ASCII string at ./lib/python3.4/site-packages/xlwt/CompoundDoc.py:210.
          Please specify the source encoding through --from-code.

**Comment by cjw296** [comment]
What command are you running and how have you installed xlwt?

**Comment by gabn88** [comment]
I'm running python3.4 manage.py makemessages -l es to add a new language. However, I have now fixed it by ignoring xlwt for translation. Not sure what caused the issues, but I have seen it before with other packages. I think it is not worth the time to fix it, and it might even by my installation. Sorry for this!
