### ISSUE TITLE
[py3] TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by Allactaga** [python-excel/xlwt#89]
When using `write_rich_text` with fonts, I'm getting error as in the subject.
It's easily fixed using `fr = b''` [here](https://github.com/python-excel/xlwt/blob/master/xlwt/UnicodeUtils.py#L75), as `pack` returns a bytes object. However maybe there are other things to take into account.

**Comment by cjw296** [comment]
What version of python are you using?

Would you be able to work up a pull request, including tests, to fix this?

**Comment by Allactaga** [comment]
```bash
> python                                                                                                                                             
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
```

I don't think I will come up with PR at some reasonable future time. At this point of my life I'm not spending too much time around my laptop.

**Comment by cjw296** [comment]
Well then, sadly, this will go unfixed...
