### ISSUE TITLE
DeprecationWarning: LOCALE flag with a str pattern is deprecated. Will be an error in 3.6

### ISSUE THREAD

**Issue by jdufresne** [python-excel/xlwt#90]
Using xlwt 1.1.2 with all warnings turned on (`python -Wall`) produces the following deprecation warning in Python 3.5:

```
.../xlwt/ExcelFormulaLexer.py:53: DeprecationWarning: LOCALE flag with a str pattern is deprecated. Will be an error in 3.6
  VERBOSE+LOCALE+IGNORECASE)
```

[The line](https://github.com/python-excel/xlwt/blob/9ccf58a3aae5759c811ff2284f0944bac42d873f/xlwt/ExcelFormulaLexer.py#L53)

[warnings module](https://docs.python.org/3/library/warnings.html)
[command line option -Wall](https://docs.python.org/3/using/cmdline.html#cmdoption-W)

**Comment by cjw296** [comment]
Please can you submit a pull request, including test coverage of the affected line?

**Comment by jdufresne** [comment]
> including test coverage of the affected line?

The line is at the top level of the module, so it already has coverage. The error was discovered with existing tests using the following command with Python 3.5:

```
$ python3 -Wall -m unittest discover -s tests
/home/jon/devel/xlwt/xlwt/ExcelFormulaLexer.py:53: DeprecationWarning: LOCALE flag with a str pattern is deprecated. Will be an error in 3.6
  VERBOSE+LOCALE+IGNORECASE)
..................
----------------------------------------------------------------------
Ran 18 tests in 0.033s

OK
```

After the change, the warning is gone.

I found more information about the Python changes [here](https://hg.python.org/cpython/rev/561d1d0de518).

**Comment by cjw296** [comment]
Okay, interesting. So, what was that LOCALE flag doing and what's the recommended way forward?

**Comment by jdufresne** [comment]
> what was that LOCALE flag doing

According to the linked Python change, nothing. It only affects regular expressions on bytes, but the one in xlwt is on Unicode strings.

> what's the recommended way forward?

Either drop it (approach I've taken) or change the regular expression to handle bytes. Do you know if formula _should_ be handled as bytes instead? I believe it is correct to leave it handling Unicode strings.

**Comment by jdufresne** [comment]
Additionally, here is [Python's description of `LOCALE`](https://docs.python.org/3/library/re.html#re.LOCALE):

>  re.LOCALE

> Make \w, \W, \b, \B, \s and \S dependent on the current locale. The use of this flag is discouraged as the locale mechanism is very unreliable, and it only handles one “culture” at a time anyway; you should use Unicode matching instead, which is the default in Python 3 for Unicode (str) patterns. This flag makes sense only with bytes patterns.

> Deprecated since version 3.5, will be removed in version 3.6: Deprecated the use of re.LOCALE with string patterns or re.ASCII.

**Comment by cjw296** [comment]
@sjmachin - opinions on this?

**Comment by jcsaaddupuy** [comment]
Hi,

python 3.6 final is annouced to be released on [2016-12-16](https://www.python.org/dev/peps/pep-0494/)
Any chance for a `xlwt` new release with this fix near this date ?

Thanks for the good work,

**Comment by sandys** [comment]
+1 - we are facing this same issue with the new 3.6

would appreciate a fix.

**Comment by mayait** [comment]
Here with the same problem

**Comment by antorix** [comment]
Hi. The same problem on 3.6. I have to recommend users not do update to 3.6 because of this.

**Comment by cjw296** [comment]
@jcsaaddupuy - done.

**Comment by jcsaaddupuy** [comment]
Thanks ! 🍾

**Comment by antorix** [comment]
Thanks. I downloaded the latest version, and it now works.
