### ISSUE TITLE
How to append new contents to old cell contents using xlrd/xlwt python modules

### ISSUE THREAD

**Issue by Thirumalesh-HS** [python-excel/xlwt#93]
Hi, I'm trying to write contents to excel sheet. I want to append new contents to old cell(say cell 0,0) contents. From the xlrd module documentation , i couldn't find a method to do it. Below is what I'm trying to do.

 ```
 from xlrd import open_workbook
 from xlwt import Workbook

 newbook = Workbook()
 newsheet = newbook.add_sheet('sample')
 newbook.save('sample.xls')

 workbook = open_workbook('sample.xls')
 sheet = workbook.get_sheet(0)

 for i in range(3):
    sheet.write(0, 0, str(i) + str(sheet.cell(0, 0).value))
```
Above statement `sheet.write(0, 0, str(i) + str(sheet.cell(0, 0).value))` throws AttributeError, since `Worksheet` object has no attribute `cell`. I would like to know the workaround to achieve this by built-in methods or should I keep track of old cell contents in some temp variables and append those with new cell contents.

Thanks

**Comment by cjw296** [comment]
This is not the mailing list.
