### ISSUE TITLE
xlwt/xlrd stopped working on Python 3.6.0

### ISSUE THREAD

**Issue by antorix** [python-excel/xlwt#94]
Hi. XLWT and XLRD don't work on Python 3.6.0. Have you already investigated this issue? For example, this simplest code:

```
import xlwt
wb = xlwt.Workbook()
ws = wb.add_sheet("My Sheet")
ws.write(0, 0, "hello")
wb.save("workbook.xls")
```

produces a lot of errors with ValueError in the end:

```
...
File "C:\Users\antor\AppData\Local\Programs\Python\Python36-32\lib\sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
```

**Comment by cfrey** [comment]
This is the same issue as described (but not yet fixed) in #90.

**Comment by cjw296** [comment]
@cfrey - really? Looks fixed to me: https://github.com/python-excel/xlwt/pull/91 (which is referred to just before #90 was closed).

This hasn't yet been released though. 

So, what's the problem with xlrd, or is @antorix just incorrectly bug reporting?

**Comment by cfrey** [comment]
Ah yes, thanks.

**Comment by cjw296** [comment]
1.2.0 now released.

**Comment by antorix** [comment]
Yes, it works now, thanks.

**Comment by ritacapela** [comment]
Hello, I'm also having this issue using: Python 3.6.2, xlrd-1.1.0,  xlwt-1.3.0
I'm asking here as last resource, i've searched everywhere, helppp
