### ISSUE TITLE
Error when format string is None

### ISSUE THREAD

**Issue by mickeydonkey** [python-excel/xlwt#98]
I cant save workbook via xlutils which depends on this project. python 2.7 and python3.4 give the same result. here is the Error information:
```
 File "C:\Users\luotao\Miniconda3\envs\py27\lib\site-packages\xlwt\Workbook.py", line 710, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "C:\Users\luotao\Miniconda3\envs\py27\lib\site-packages\xlwt\Workbook.py", line 667, in get_biff_data
    before += self.__all_fonts_num_formats_xf_styles_rec()
  File "C:\Users\luotao\Miniconda3\envs\py27\lib\site-packages\xlwt\Workbook.py", line 570, in __all_fonts_num_formats_xf_styles_rec
    return self.__styles.get_biff_data()
  File "C:\Users\luotao\Miniconda3\envs\py27\lib\site-packages\xlwt\Style.py", line 185, in get_biff_data
    result += self._all_num_formats()
  File "C:\Users\luotao\Miniconda3\envs\py27\lib\site-packages\xlwt\Style.py", line 210, in _all_num_formats
    result += NumberFormatRecord(fmtidx, fmtstr).get()
  File "C:\Users\luotao\Miniconda3\envs\py27\lib\site-packages\xlwt\BIFFRecords.py", line 785, in __init__
    ufmtstr = upack2(fmtstr)
  File "C:\Users\luotao\Miniconda3\envs\py27\lib\site-packages\xlwt\UnicodeUtils.py", line 50, in upack2
    us = unicode(s, encoding)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
The error comes from this function `_all_num_formats` when `fmtidx, fmtstr= 183, None`, However, the workbook can be saved when I wrapper the error with try....except... , . 
```
    def _all_num_formats(self):
        result = b''
        alist = [
            (v, k)
            for k, v in self._num_formats.items()
            if v >= FIRST_USER_DEFINED_NUM_FORMAT_IDX
            ]
        alist.sort()
        for fmtidx, fmtstr in alist:
            #try:
            result += NumberFormatRecord(fmtidx, fmtstr).get()
            # except:
            #     print (fmtidx, fmtstr)
        return result
```

**Comment by jdufresne** [comment]
Can you provide a minimal example script to reproduce? If required to reproduce, please also provide an xls document. Thanks.

**Comment by beimingmaster** [comment]
~/.virtualenvs/dl4cv/lib/python3.5/site-packages/xlwt/Workbook.py in save(self, filename_or_stream)
    708 
    709         doc = CompoundDoc.XlsDoc()
--> 710         doc.save(filename_or_stream, self.get_biff_data())
    711 
    712 

~/.virtualenvs/dl4cv/lib/python3.5/site-packages/xlwt/Workbook.py in get_biff_data(self)
    665         before += self.__refresh_all_rec()
    666         before += self.__bookbool_rec()
--> 667         before += self.__all_fonts_num_formats_xf_styles_rec()
    668         before += self.__palette_rec()
    669         before += self.__useselfs_rec()

~/.virtualenvs/dl4cv/lib/python3.5/site-packages/xlwt/Workbook.py in __all_fonts_num_formats_xf_styles_rec(self)
    568 
    569     def __all_fonts_num_formats_xf_styles_rec(self):
--> 570         return self.__styles.get_biff_data()
    571 
    572     def __palette_rec(self):

~/.virtualenvs/dl4cv/lib/python3.5/site-packages/xlwt/Style.py in get_biff_data(self)
    183         result = b''
    184         result += self._all_fonts()
--> 185         result += self._all_num_formats()
    186         result += self._all_cell_styles()
    187         result += self._all_styles()

~/.virtualenvs/dl4cv/lib/python3.5/site-packages/xlwt/Style.py in _all_num_formats(self)
    207         alist.sort()
    208         for fmtidx, fmtstr in alist:
--> 209             result += NumberFormatRecord(fmtidx, fmtstr).get()
    210         return result
    211 

~/.virtualenvs/dl4cv/lib/python3.5/site-packages/xlwt/BIFFRecords.py in __init__(self, idx, fmtstr)
    783 
    784     def __init__(self, idx, fmtstr):
--> 785         ufmtstr = upack2(fmtstr)
    786         ufmtstr_len = len(ufmtstr)
    787 

~/.virtualenvs/dl4cv/lib/python3.5/site-packages/xlwt/UnicodeUtils.py in upack2(s, encoding)
     48         us = s
     49     else:
---> 50         us = unicode(s, encoding)
     51     # Limit is based on number of content characters
     52     # (not on number of bytes in packed result)

TypeError: descriptor 'decode' requires a 'bytes' object but received a 'NoneType'



--> 209             result += NumberFormatRecord(fmtidx, fmtstr).get()

when value of “fmtstr” is None, this error will occur

**Comment by beimingmaster** [comment]
i found color of cell  is not consistent with source file

**Comment by cjw296** [comment]
No feedback.
